# Generated by Django 5.0.8 on 2024-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoices_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='file_path',
            field=models.URLField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='reference',
            field=models.CharField(blank=True, null=True),
        ),
    ]
