# Generated by Django 5.0.8 on 2024-08-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoices_currency_code_invoices_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='issuedat',
            new_name='issuedate',
        ),
    ]
