# Generated by Django 5.0.8 on 2024-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_dunningplan_is_disabled_invoices_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Due'), (1, 'Partial'), (2, 'Completed'), (3, 'Writeoff')], default=0, null=True),
        ),
    ]
