# Generated by Django 5.0.8 on 2024-10-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='avatax_tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='avatax_use_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='is_discount_before_tax',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='is_inclusive_tax',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='payment_terms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='payment_terms_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tax_authority_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='total_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceCustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_custom_fields', to='invoices.invoices')),
            ],
            options={
                'db_table': 'inv_custom_fields',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=50)),
                ('hsn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoices.invoices')),
            ],
            options={
                'db_table': 'invoice_details',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(max_length=50)),
                ('configured', models.BooleanField(blank=True, default=False, null=True)),
                ('additional_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='invoices.invoices')),
            ],
            options={
                'db_table': 'payment_gateways',
            },
        ),
    ]
