# Generated by Django 5.0.8 on 2024-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_rename_discount_invoicedetails_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
