# Generated by Django 5.0.8 on 2024-08-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_emailtrigger_trigger_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrigger',
            name='days_offset',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trigger_rule',
            name='days_offset',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trigger_rule',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
