# Generated by Django 5.0.8 on 2024-10-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_account_address_account_credit_limit_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customers',
            name='crm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_category',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('premium', 'Premium'), ('delinquent', 'Delinquent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='erp_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='creditlimit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('finance_manager', 'Finance Manager'), ('ar_specialist', 'Accounts Receivable Specialist'), ('ceo', 'CEO'), ('cfo', 'CFO'), ('accountant', 'Accountant'), ('billing_manager', 'Billing Manager'), ('collections_agent', 'Collections Agent'), ('ap_specialist', 'Accounts Payable Specialist'), ('customer_service', 'Customer Service Representative'), ('sales_rep', 'Sales Representative'), ('legal', 'Legal Counsel'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.customers')),
            ],
        ),
    ]
