# Generated by Django 5.0.8 on 2024-10-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_emailtrigger_days_offset_emailtrigger_isactive_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_provider',
            },
        ),
        migrations.CreateModel(
            name='GlobalEmailSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_sender_email', models.EmailField(max_length=254)),
                ('default_dkim_selector', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'global_email_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('dkim_selector', models.CharField(blank=True, max_length=50, null=True)),
                ('dkim_public_key', models.TextField(blank=True, null=True)),
                ('dkim_private_key', models.TextField(blank=True, null=True)),
                ('spf_record', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.emailprovider')),
            ],
            options={
                'db_table': 'email_configuration',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('verification_type', models.CharField(max_length=10)),
                ('is_disabled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('email_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.emailconfiguration')),
            ],
            options={
                'db_table': 'email_verification_log',
            },
        ),
    ]
