# Generated by Django 5.0.8 on 2024-10-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailprovider_globalemailsettings_emailconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.emailprovider'),
        ),
    ]
