# Generated by Django 5.0.8 on 2024-10-12 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailconfiguration_email_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='daily_send_limit',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='dmarc_pct',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='dmarc_policy',
            field=models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='dmarc_record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='is_dmarc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SendingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('email_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.emailconfiguration')),
            ],
            options={
                'unique_together': {('email_configuration', 'date')},
            },
        ),
    ]
