# Generated by Django 5.0.8 on 2024-10-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailconfiguration_daily_send_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='is_spf_verified',
            field=models.BooleanField(default=False),
        ),
    ]
