# Generated by Django 5.0.8 on 2024-10-12 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_account_address_account_credit_limit_account_email_and_more'),
        ('users', '0005_emailconfiguration_is_spf_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domainconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mail_from_domain', models.CharField(max_length=255)),
                ('spf_record', models.TextField()),
                ('dmarc_record', models.TextField()),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('DKIM', 'DKIM')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('selector', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domainconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.domainconfig')),
            ],
            options={
                'db_table': 'DNSRecord',
            },
        ),
    ]
