# Generated by Django 5.0.8 on 2024-10-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_domainconfig_dnsrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domainconfig',
            table='Domainconfig',
        ),
    ]
