# Generated by Django 5.0.8 on 2024-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_account_address_account_credit_limit_account_email_and_more'),
        ('users', '0007_alter_domainconfig_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this domain is the default for the account'),
        ),
        migrations.AddField(
            model_name='domainconfig',
            name='send_mail_from',
            field=models.EmailField(blank=True, help_text='Email address to send mail from for this domain', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='domainconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_disabled', False)), fields=('name', 'account'), name='unique_domain_per_account'),
        ),
    ]
