# Generated by Django 5.0.8 on 2024-10-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_send_mail_from_domainconfig_mailing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
